---
- group: name=sudo state=present

- name: Allow '{{ deploy_user }}' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{deploy_user}}'
    line: '%{{deploy_user}} ALL=(ALL) NOPASSWD: ALL'
  become: yes
  become_method: sudo

- name: Add deployer user and add it to sudo
  user: name={{ deploy_user }}
        state=present
        createhome=yes
        generate_ssh_key=yes
        shell=/bin/bash
        groups=sudo
  become: yes
  become_method: sudo

- name: Set up authorized keys for the deployer user
  tags: 'authorized_keys'
  authorized_key: user={{ deploy_user }} key="{{item}}" manage_dir=yes
  become: yes
  become_user: '{{ deploy_user }}'
  with_lines: 
    - "cat public_keys/authorized_keys/*.pub"
  notify:
    - nori-rdoc

- name: Copy the ssh keys for git clone
  become: yes
  become_user: '{{ deploy_user }}'
  copy: src={{ item.src }} dest={{ item.dest }} mode=0600
  with_items:
    - { src: public_keys/deploy.pub, dest: '/home/{{ deploy_user }}/.ssh/id_rsa.pub'}
    - { src: public_keys/deploy, dest: '/home/{{ deploy_user }}/.ssh/id_rsa' }

- name: 'Create {{ deploy_to }} directory'
  become: yes
  become_method: sudo
  file: path={{ deploy_to }} state=directory owner={{ deploy_user }} group={{ deploy_user }} mode=0755 recurse=yes

